#+title: Readme

* Motivation
This is my first iteration in escaping the abyss that I've for year been sinking into.
After many projects and setups, I recognized the same pattern, 1) Setup my system 2) Add configurations 3) Forget why (or that I added) a configuration in the first place 4) Revisting configs and get lost in the mess.
It was time to escape and .org repository is the first iteration in trying to do so.

I started this project without any intention in sharing it, it's just a collection of literate dotfiles. If used locally, be careful noting that this is just for reference and ultimately you not run any code from this repo without knowing what's going on.

* Structure
Each subdirectory relates to one configuration file on the host system.
Configuration files in each subdirectory are tangled with the taget configuration file defined in the header.

*** [CONFIG-DIRECTORY]/configname.org
Main configuration, using tangle and noweb to target specific configuration files on the system.
*** [CONFIG-DIRECTORY]/config.org
Contains configuration blocks inheirited to `configname.org`.
*** [CONFIG-DIRECTORY]/secrets.org
Contains encrypted configuration blocks inheirited to `configname.org`. [not stored in git]
Template available under `util/secrets.template.org`
* Makefile
** Prerequisites
- [[https://github.com/roswell/roswell][Roswell]]
** Build tangle script
#+begin_src shell
make build
#+end_src
** Tangle .org files with dotfiles
#+begin_src shell
make tangle
#+end_src
